### ISSUE TITLE
Airplane Crash: Export not working

### ISSUE THREAD

**Issue by dpdavids** [ytgov/yhsi#148]
on the grid screen On selecting the export button rather than a download of a .CSV happens rather I receive the below error
"A problem has occurred, please check your internet connection"

**Comment by ryanjagar** [comment]
In initial testing, I cannot duplicate this. Clicking on the button triggers a download of a CSV.

<img width="1494" alt="image" src="https://github.com/ytgov/yhsi/assets/49032969/82fab38a-ef5c-45e1-9a2f-2d13565f9695">

<img width="961" alt="image" src="https://github.com/ytgov/yhsi/assets/49032969/8986fdc6-4793-4454-b7f2-70d81cc71f07">

**Comment by ryanjagar** [comment]
Tested in commit [416d796](https://github.com/ytgov/yhsi/commit/416d796c91ccf82338cb7a3a8a33aea98ded7eeb) it seems to be working.  @dpdavids would you test to confirm?

**Comment by dpdavids** [comment]
this appears to work now
