### ISSUE TITLE
AirplaneCrash: Filters

### ISSUE THREAD

**Issue by dpdavids** [ytgov/yhsi#93]
The Filter tool does not function.  No search terms work on any of the filter items.

**Comment by dpdavids** [comment]
The filter tool now works but it is not terribly user friendly.
The user picks a field to search and keys in a search term.  The table behind is not actively changing as you type so the user hits enter and doesn't see change.  It is not until the user navigates away from the filter drop down that the filter can be seen.

Consider a Filter button at the bottom of the pop-up that closes the filter widow and update the grid to reflect the filtering.  However once the filter section has been navigated away from there is not method to define if there are any filters still left on.

**Comment by ryanjagar** [comment]
Addressed by https://github.com/ytgov/yhsi/pull/154/commits/5de67dd2ac62057dfea79fe21077fbebd8b1d2e5
